version: '3.9'

services:
  #reverse proxy
  nginx-reverse-proxy:
    build:
      context: containers/nginx-reverse-proxy
      dockerfile: nginx-proxy.Dockerfile
    ports:
      - "443:443"
    environment:
      - FQDN

  #backend application
  uvicorn-backend:
    hostname: uvicorn-backend
    build:
      context: .
      dockerfile: uvicorn-backend.Dockerfile
    environment:
      - OPENAPI_KEY