version: '3.9'

services:
  #reverse proxy
  nginx-reverse-proxy:
    build:
      context: containers/nginx-reverse-proxy
      dockerfile: nginx-proxy.Dockerfile
    ports:
      - "443:443"

  #backend application
  uvicorn-backend:
    hostname: uvicorn-backend
    environment:
      - OPENAPI_KEY=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
    build:
      context: .
      dockerfile: uvicorn-backend.Dockerfile